# Generated by Django 2.2.5 on 2019-10-18 14:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('client_img', models.ImageField(null=True, upload_to='client_img/')),
            ],
        ),
        migrations.CreateModel(
            name='CLP',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('model', models.CharField(blank=True, max_length=200, null=True)),
                ('ip_int', models.CharField(max_length=200)),
                ('ip_ext', models.CharField(max_length=200)),
                ('port', models.IntegerField(default=0)),
                ('clp_img', models.ImageField(blank=True, null=True, upload_to='clp_img/')),
                ('client', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='clients.Client')),
            ],
        ),
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'permissions': [('escritorio', 'Tela Escritório'), ('cnb', 'Tela CNB')],
            },
        ),
        migrations.CreateModel(
            name='Equipamento',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('model', models.CharField(blank=True, max_length=200, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('end_modbus_leitura', models.IntegerField(default=0)),
                ('end_modbus_escrita', models.IntegerField(default=0)),
                ('status', models.CharField(blank=True, max_length=200, null=True)),
                ('equip_img', models.ImageField(blank=True, null=True, upload_to='equip_img/')),
                ('client', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='clients.Client')),
                ('clp', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='clients.CLP')),
            ],
        ),
    ]
