# Generated by Django 2.2.5 on 2019-10-24 18:25

import datetime
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Value',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.IntegerField()),
                ('date', models.DateTimeField(default=datetime.datetime(2019, 10, 24, 18, 25, 41, 1078, tzinfo=utc))),
                ('clp', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='clients.CLP')),
            ],
        ),
    ]
