# Generated by Django 2.2.5 on 2019-10-02 20:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='clp',
            name='client',
        ),
        migrations.AddField(
            model_name='clp',
            name='client',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='clients.Client'),
        ),
    ]
