# Generated by Django 2.2.5 on 2019-10-03 17:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0004_auto_20191003_1347'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='task',
            options={'permissions': [('escritorio', 'Tela Escritório'), ('cnb', 'Tela CNB')]},
        ),
    ]
