# Generated by Django 2.2.5 on 2019-10-07 19:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0005_auto_20191003_1443'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='client_img',
            field=models.ImageField(null=True, upload_to='static/client_img'),
        ),
        migrations.AddField(
            model_name='clp',
            name='clp_img',
            field=models.ImageField(null=True, upload_to='static/clp_img'),
        ),
        migrations.AddField(
            model_name='equipamento',
            name='equip_img',
            field=models.ImageField(null=True, upload_to='static/equip_img'),
        ),
    ]
