# Generated by Django 2.2.5 on 2019-10-24 18:38

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0005_auto_20191024_1537'),
    ]

    operations = [
        migrations.AddField(
            model_name='value',
            name='end',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='value',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2019, 10, 24, 18, 38, 32, 815536, tzinfo=utc)),
        ),
    ]
