# Generated by Django 2.2.5 on 2019-10-07 19:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0006_auto_20191007_1611'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='client_img',
            field=models.ImageField(null=True, upload_to='2/change/static/client_img/'),
        ),
    ]
