# Generated by Django 2.2.5 on 2019-10-07 19:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0007_auto_20191007_1623'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='client_img',
            field=models.ImageField(null=True, upload_to='client_img/'),
        ),
        migrations.AlterField(
            model_name='clp',
            name='clp_img',
            field=models.ImageField(null=True, upload_to='clp_img/'),
        ),
        migrations.AlterField(
            model_name='equipamento',
            name='equip_img',
            field=models.ImageField(null=True, upload_to='equip_img/'),
        ),
    ]
