# Generated by Django 2.2.5 on 2019-10-18 13:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0008_auto_20191007_1639'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clp',
            name='clp_img',
            field=models.ImageField(blank=True, null=True, upload_to='clp_img/'),
        ),
        migrations.AlterField(
            model_name='equipamento',
            name='equip_img',
            field=models.ImageField(blank=True, null=True, upload_to='equip_img/'),
        ),
    ]
